### ISSUE TITLE
Minor code error

### ISSUE THREAD

**Issue by jallwork** [alexa-samples/skill-sample-plant-care-widget#1]
Minor detail, but line 111 in lambda/index.js

console.log("From Version" + handlerInput.requestEnvelope.request.toVersion);

should be:

console.log("ToVersion" + handlerInput.requestEnvelope.request.toVersion);

**Comment by aszk** [comment]
Note: https://github.com/alexa-samples/skill-sample-plant-care-widget/blob/main/lambda/index.js#L111

**Comment by pkarthikr** [comment]
Fixed in latest [commit](https://github.com/alexa-samples/skill-sample-plant-care-widget/commit/c16ac73353e73167acb3046a840fe3d16172b35b). Thanks for reporting @jallwork
